export enum ActionType {


    //LOGIN / USER ACTION TYPES ---------------------------------
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    SIGNIN = 'SIGNIN',
    REGISTER = 'REGISTER',
    SIGNOUT = 'SIGNOUT',
    SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED',
    GET_USER_DATA = 'GET_USER_DATA',
    SET_USER_DATA = 'SET_USER_DATA',

    //PLANT ACTION TYPES ---------------------------------

    SET_PLANTS = 'SET_PLANTS',




    TOGGLE_IS_NOTIFIED = 'TOGGLE_IS_NOTIFIED',
    UPDATE_INPUT = 'UPDATE_INPUT',
    CLEAR_INPUT = 'CLEAR_INPUT',
    USE_INJECTION = 'USE_INJECTION',
}